# Generated by Django 6.0.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, help_text="Kode provinsi (dari data Kemendagri/ibnux).", max_length=10, unique=True, verbose_name="kode")),
                ("name", models.CharField(help_text="Nama provinsi (contoh: SUMATERA UTARA).", max_length=255, verbose_name="nama")),
            ],
            options={
                "verbose_name": "provinsi",
                "verbose_name_plural": "daftar provinsi",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Regency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, help_text="Kode kabupaten/kota (dari data Kemendagri/ibnux).", max_length=10, unique=True, verbose_name="kode")),
                ("name", models.CharField(help_text="Nama kabupaten/kota (contoh: KAB. ASAHAN, KOTA MEDAN).", max_length=255, verbose_name="nama")),
                ("province", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="regencies", to="regions.province", verbose_name="provinsi")),
            ],
            options={
                "verbose_name": "kabupaten / kota",
                "verbose_name_plural": "daftar kabupaten / kota",
                "ordering": ["province", "name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, help_text="Kode kecamatan (dari data Kemendagri/ibnux).", max_length=10, unique=True, verbose_name="kode")),
                ("name", models.CharField(help_text="Nama kecamatan.", max_length=255, verbose_name="nama")),
                ("regency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="districts", to="regions.regency", verbose_name="kabupaten / kota")),
            ],
            options={
                "verbose_name": "kecamatan",
                "verbose_name_plural": "daftar kecamatan",
                "ordering": ["regency", "name"],
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, help_text="Kode kelurahan/desa (dari data Kemendagri/ibnux).", max_length=10, unique=True, verbose_name="kode")),
                ("name", models.CharField(help_text="Nama kelurahan/desa.", max_length=255, verbose_name="nama")),
                ("district", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="villages", to="regions.district", verbose_name="kecamatan")),
            ],
            options={
                "verbose_name": "kelurahan / desa",
                "verbose_name_plural": "daftar kelurahan / desa",
                "ordering": ["district", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="regency",
            index=models.Index(fields=["province"], name="regions_regency_province_idx"),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(fields=["regency"], name="regions_district_regency_idx"),
        ),
        migrations.AddIndex(
            model_name="village",
            index=models.Index(fields=["district"], name="regions_village_district_idx"),
        ),
    ]
