# Generated by Django 6.0.2 on 2026-02-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='district',
            new_name='regions_dis_regency_0a3d69_idx',
            old_name='regions_district_regency_idx',
        ),
        migrations.RenameIndex(
            model_name='regency',
            new_name='regions_reg_provinc_172a18_idx',
            old_name='regions_regency_province_idx',
        ),
        migrations.RenameIndex(
            model_name='village',
            new_name='regions_vil_distric_954e5d_idx',
            old_name='regions_village_district_idx',
        ),
    ]
