# Generated by Django 6.0.2 on 2026-03-05 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(db_index=True, default=False, help_text='Admin dapat menutup thread sehingga tidak ada pesan baru yang dapat dikirim.', verbose_name='ditutup')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Diperbarui setiap kali pesan baru dikirim — digunakan untuk mengurutkan thread.', verbose_name='diperbarui pada')),
                ('application', models.OneToOneField(help_text='Lamaran kerja yang terkait dengan thread ini.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_thread', to='main.jobapplication', verbose_name='lamaran')),
            ],
            options={
                'verbose_name': 'thread obrolan',
                'verbose_name_plural': 'daftar thread obrolan',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Teks pesan.', verbose_name='isi pesan')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='dikirim pada')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='True setelah penerima membaca pesan ini.', verbose_name='sudah dibaca')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='dibaca pada')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='pengirim')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatthread', verbose_name='thread')),
            ],
            options={
                'verbose_name': 'pesan obrolan',
                'verbose_name_plural': 'daftar pesan obrolan',
                'ordering': ['sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['is_closed', 'updated_at'], name='chat_chatth_is_clos_dccdfe_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'sent_at'], name='chat_chatme_thread__d53411_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'sent_at', 'is_read'], name='chat_chatme_thread__602fc6_idx'),
        ),
    ]
