# Generated by Django 6.0.2 on 2026-02-18 04:01

import account.models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, help_text='Digunakan untuk login dan notifikasi.', max_length=254, unique=True, verbose_name='alamat email')),
                ('full_name', models.CharField(blank=True, help_text='Nama lengkap pengguna (untuk Admin; peran lain dapat memakai profil).', max_length=255, verbose_name='nama lengkap')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staf'), ('COMPANY', 'Perusahaan'), ('APPLICANT', 'Pelamar')], db_index=True, default='APPLICANT', help_text='Menentukan akses dan profil (staf/pelamar/perusahaan) yang berlaku.', max_length=9, verbose_name='peran')),
                ('email_verified', models.BooleanField(db_index=True, default=False, help_text='Apakah alamat email sudah diverifikasi.', verbose_name='email terverifikasi')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='Waktu email diverifikasi.', null=True, verbose_name='email terverifikasi pada')),
                ('google_id', models.CharField(blank=True, db_index=True, help_text='ID subjek Google OAuth untuk login sosial.', max_length=255, null=True, unique=True, verbose_name='Google ID')),
                ('referral_code', models.CharField(blank=True, db_index=True, help_text='Kode rujukan unik untuk Staff/Admin. Pelamar harus memasukkan kode ini saat registrasi.', max_length=16, null=True, unique=True, verbose_name='kode rujukan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'pengguna',
                'verbose_name_plural': 'daftar pengguna',
                'ordering': ['-is_active', 'email'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(blank=True, help_text='Tanggal pendaftaran (hari ini saat mengisi form).', null=True, verbose_name='tanggal pendaftaran')),
                ('destination_country', models.CharField(blank=True, choices=[('MALAYSIA', 'Malaysia')], default='MALAYSIA', help_text='Negara tujuan penempatan (form: RBA zero cost).', max_length=20, verbose_name='negara yang dituju')),
                ('birth_place', models.CharField(blank=True, max_length=255, verbose_name='tempat lahir')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='tanggal lahir')),
                ('address', models.TextField(blank=True, help_text='Alamat sesuai KTP (lengkap sampai Kota/Kabupaten).', verbose_name='alamat sesuai KTP')),
                ('contact_phone', models.CharField(blank=True, help_text='Nomor HP/WA yang aktif.', max_length=50, verbose_name='no. HP / WA yang aktif')),
                ('sibling_count', models.PositiveSmallIntegerField(blank=True, help_text='Jumlah saudara.', null=True, verbose_name='jumlah saudara')),
                ('birth_order', models.PositiveSmallIntegerField(blank=True, help_text='Anak ke- (urutan lahir dalam keluarga).', null=True, verbose_name='anak ke')),
                ('father_name', models.CharField(blank=True, help_text='Nama ayah kandung.', max_length=255, verbose_name='nama ayah')),
                ('father_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='umur ayah')),
                ('father_occupation', models.CharField(blank=True, max_length=255, verbose_name='pekerjaan ayah')),
                ('mother_name', models.CharField(blank=True, help_text='Nama ibu kandung.', max_length=255, verbose_name='nama ibu')),
                ('mother_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='umur ibu')),
                ('mother_occupation', models.CharField(blank=True, max_length=255, verbose_name='pekerjaan ibu')),
                ('spouse_name', models.CharField(blank=True, help_text='Nama suami atau istri (jika sudah menikah).', max_length=255, verbose_name='nama suami / istri')),
                ('spouse_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='umur suami / istri')),
                ('spouse_occupation', models.CharField(blank=True, max_length=255, verbose_name='pekerjaan suami / istri')),
                ('family_address', models.TextField(blank=True, help_text='Alamat orangtua/keluarga (lengkap sampai Kota/Kabupaten).', verbose_name='alamat orangtua / keluarga')),
                ('family_contact_phone', models.CharField(blank=True, help_text='Nomor HP/WA keluarga yang aktif.', max_length=50, verbose_name='no. HP / WA keluarga yang aktif')),
                ('data_declaration_confirmed', models.BooleanField(default=False, help_text='Apakah data yang diisi benar dan dapat dipertanggungjawabkan (YA/TIDAK).', verbose_name='pernyataan data benar')),
                ('zero_cost_understood', models.BooleanField(default=False, help_text='Paham bahwa proses penempatan 0 (nol) biaya ditanggung perusahaan.', verbose_name='paham zero cost')),
                ('nik', models.CharField(db_index=True, help_text='Nomor Induk Kependudukan (NIK). 16 digit, unik per pelamar. Wajib diisi saat pendaftaran (dari KTP atau input manual).', max_length=16, unique=True, verbose_name='NIK')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Laki-laki'), ('F', 'Perempuan'), ('O', 'Lainnya')], max_length=1, verbose_name='jenis kelamin')),
                ('religion', models.CharField(blank=True, choices=[('ISLAM', 'Islam'), ('KRISTEN', 'Kristen'), ('KATHOLIK', 'Katholik'), ('HINDU', 'Hindu'), ('BUDHA', 'Budha'), ('LAINNYA', 'Lainnya')], max_length=8, verbose_name='agama')),
                ('education_level', models.CharField(blank=True, choices=[('SMP', 'SMP'), ('SMA', 'SMA'), ('SMK', 'SMK'), ('MA', 'MA'), ('D3', 'D3'), ('S1', 'S1')], max_length=3, verbose_name='pendidikan terakhir')),
                ('education_major', models.CharField(blank=True, max_length=255, verbose_name='jurusan pendidikan')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, help_text='Tinggi badan dalam centimeter.', null=True, verbose_name='tinggi badan (cm)')),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, help_text='Berat badan dalam kilogram.', null=True, verbose_name='berat badan (kg)')),
                ('wears_glasses', models.BooleanField(blank=True, help_text='Apakah memakai kacamata (YA/TIDAK).', null=True, verbose_name='memakai kacamata (mata minus)')),
                ('writing_hand', models.CharField(blank=True, choices=[('KANAN', 'Kanan'), ('KIRI', 'Kiri')], max_length=5, verbose_name='menulis dengan tangan')),
                ('marital_status', models.CharField(blank=True, choices=[('BELUM MENIKAH', 'Belum Menikah'), ('MENIKAH', 'Menikah'), ('CERAI HIDUP', 'Cerai Hidup'), ('CERAI MATI', 'Cerai Mati')], max_length=14, verbose_name='status perkawinan')),
                ('has_passport', models.BooleanField(blank=True, help_text='Apakah memiliki paspor (YA/TIDAK).', null=True, verbose_name='memiliki paspor')),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='nomor paspor')),
                ('passport_issue_date', models.DateField(blank=True, help_text='Tanggal paspor diterbitkan.', null=True, verbose_name='tanggal terbit paspor')),
                ('passport_expiry_date', models.DateField(blank=True, null=True, verbose_name='tanggal berakhir masa berlaku paspor')),
                ('passport_issue_place', models.CharField(blank=True, help_text='Kota/lokasi paspor diterbitkan (contoh: Jakarta).', max_length=100, verbose_name='tempat terbit paspor')),
                ('family_card_number', models.CharField(blank=True, help_text='Nomor KK.', max_length=50, verbose_name='nomor kartu keluarga')),
                ('diploma_number', models.CharField(blank=True, max_length=100, verbose_name='nomor ijazah')),
                ('bpjs_number', models.CharField(blank=True, max_length=50, verbose_name='nomor BPJS kesehatan / KIS')),
                ('shoe_size', models.CharField(blank=True, max_length=20, verbose_name='ukuran sepatu')),
                ('shirt_size', models.CharField(blank=True, help_text='Contoh: S, M, L, XL, XXL.', max_length=20, verbose_name='ukuran baju')),
                ('photo', models.ImageField(blank=True, help_text='Pas photo berwarna background putih ukuran 3x4.', null=True, upload_to='account/applicants/%Y/%m/', verbose_name='pas photo PMI')),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan (III. Keterangan).', verbose_name='keterangan')),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draf'), ('SUBMITTED', 'Dikirim'), ('ACCEPTED', 'Diterima'), ('REJECTED', 'Ditolak')], db_index=True, default='DRAFT', help_text='Draf: mengisi data. Dikirim: menunggu admin. Diterima/Ditolak: setelah verifikasi.', max_length=9, verbose_name='status verifikasi')),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, help_text='Waktu pelamar mengirim untuk verifikasi (status → Dikirim).', null=True, verbose_name='dikirim pada')),
                ('verified_at', models.DateTimeField(blank=True, db_index=True, help_text='Waktu admin menetapkan status Diterima atau Ditolak.', null=True, verbose_name='diverifikasi pada')),
                ('verification_notes', models.TextField(blank=True, help_text='Catatan internal atau alasan penolakan yang ditampilkan ke pelamar.', verbose_name='catatan verifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('district', models.ForeignKey(blank=True, help_text='Kota atau Kabupaten sesuai KTP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_profiles_district', to='regions.regency', verbose_name='kota / kabupaten')),
                ('family_district', models.ForeignKey(blank=True, help_text='Kota/Kabupaten alamat keluarga.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_profiles_family_district', to='regions.regency', verbose_name='kota / kabupaten (keluarga)')),
                ('family_province', models.ForeignKey(blank=True, help_text='Provinsi alamat keluarga.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_profiles_family', to='regions.province', verbose_name='provinsi (keluarga)')),
                ('family_village', models.ForeignKey(blank=True, help_text='Pilih kelurahan/desa untuk alamat keluarga.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_profiles_family_address', to='regions.village', verbose_name='kelurahan / desa (alamat keluarga)')),
                ('province', models.ForeignKey(blank=True, help_text='Provinsi sesuai KTP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_profiles', to='regions.province', verbose_name='provinsi')),
                ('referrer', models.ForeignKey(blank=True, help_text='Staf atau Admin yang merujuk pelamar ini. Jika kosong, dianggap Admin.', limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_applicants', to=settings.AUTH_USER_MODEL, verbose_name='perujuk')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'APPLICANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin atau Staf yang memverifikasi pelamar ini.', limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_applicants', to=settings.AUTH_USER_MODEL, verbose_name='diverifikasi oleh')),
                ('village', models.ForeignKey(blank=True, help_text='Pilih kelurahan/desa untuk alamat KTP (provinsi, kabupaten, kecamatan terisi otomatis).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_profiles_address', to='regions.village', verbose_name='kelurahan / desa (alamat KTP)')),
            ],
            options={
                'verbose_name': 'profil pelamar',
                'verbose_name_plural': 'daftar profil pelamar',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Nama perusahaan terdaftar.', max_length=255, verbose_name='nama perusahaan')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='telepon kontak')),
                ('address', models.TextField(blank=True, verbose_name='alamat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'profil perusahaan',
                'verbose_name_plural': 'daftar profil perusahaan',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Kode unik (mis. ktp, ijasah, kk).', unique=True, verbose_name='kode')),
                ('name', models.CharField(help_text='Nama tampilan (mis. KTP, Ijasah).', max_length=255, verbose_name='nama')),
                ('is_required', models.BooleanField(default=True, help_text='Apakah dokumen ini wajib untuk pendaftaran/penempatan.', verbose_name='wajib')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Urutan di daftar (angka lebih kecil tampil lebih dulu).', verbose_name='urutan')),
                ('description', models.CharField(blank=True, help_text='Petunjuk opsional (mis. Paspor bagi yang sudah ada).', max_length=500, verbose_name='deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
            ],
            options={
                'verbose_name': 'tipe dokumen',
                'verbose_name_plural': 'daftar tipe dokumen',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['code'], name='account_doc_code_958aa3_idx'), models.Index(fields=['is_required', 'sort_order'], name='account_doc_is_requ_af3b60_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Berkas dokumen yang diunggah.', upload_to=account.models.applicant_document_upload_to, verbose_name='berkas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='diunggah pada')),
                ('ocr_text', models.TextField(blank=True, help_text='Teks penuh dari OCR (mis. Google Vision).', verbose_name='teks OCR')),
                ('ocr_data', models.JSONField(blank=True, default=dict, help_text='Data terstruktur dari OCR untuk mengisi biodata. Untuk KTP: nik, nama, tempat_lahir, tanggal_lahir, alamat, jenis_kelamin.', verbose_name='data hasil OCR')),
                ('ocr_processed_at', models.DateTimeField(blank=True, help_text='Waktu ekstraksi OCR terakhir dijalankan untuk dokumen ini.', null=True, verbose_name='diproses OCR pada')),
                ('review_status', models.CharField(choices=[('PENDING', 'Menunggu Review'), ('APPROVED', 'Diterima'), ('REJECTED', 'Ditolak')], db_index=True, default='PENDING', help_text='Status review dokumen oleh admin/staff.', max_length=8, verbose_name='status review')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Waktu dokumen direview (APPROVED atau REJECTED).', null=True, verbose_name='direview pada')),
                ('review_notes', models.TextField(blank=True, help_text='Catatan admin/staff terkait review dokumen (mis. alasan ditolak, catatan khusus).', verbose_name='catatan review')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin atau Staff yang mereview dokumen ini.', limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='direview oleh')),
                ('applicant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='account.applicantprofile', verbose_name='profil pelamar')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_documents', to='account.documenttype', verbose_name='tipe dokumen')),
            ],
            options={
                'verbose_name': 'dokumen pelamar',
                'verbose_name_plural': 'daftar dokumen pelamar',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(blank=True, help_text='Nomor telepon kontak.', max_length=50, verbose_name='telepon kontak')),
                ('photo', models.ImageField(blank=True, help_text='Foto profil staf.', null=True, upload_to='account/staff/%Y/%m/', verbose_name='foto profil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'profil staf',
                'verbose_name_plural': 'daftar profil staf',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Nama perusahaan atau pemberi kerja (form: contoh PT. MAJU JAYA - MEDAN).', max_length=255, verbose_name='nama perusahaan / pemberi kerja')),
                ('location', models.CharField(blank=True, help_text='Kota atau lokasi perusahaan (form: nama perusahaan dan kotanya).', max_length=255, verbose_name='kota / lokasi perusahaan')),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Negara tempat bekerja (ISO 3166-1 alpha-2, e.g. ID, MY).', max_length=2, verbose_name='negara tempat bekerja')),
                ('industry_type', models.CharField(blank=True, choices=[('SEMICONDUCTOR', 'Semiconductor'), ('ELEKTRONIK', 'Elektronik'), ('PABRIK LAIN', 'Pabrik Lain'), ('JASA', 'Jasa'), ('LAIN LAIN', 'Lain Lain'), ('BELUM PERNAH BEKERJA', 'Belum Pernah Bekerja')], help_text='Semiconductor, Elektronik, Pabrik Lain, Jasa, Lain Lain, Belum Pernah Bekerja.', max_length=21, verbose_name='jenis industri perusahaan')),
                ('position', models.CharField(blank=True, help_text='Jabatan (contoh: Operator, Leader, Supervisor).', max_length=255, verbose_name='jabatan / posisi')),
                ('department', models.CharField(blank=True, help_text='Bagi pekerja kilang/pabrik: QC, SMT, Moulding, Packing, dll.', max_length=255, verbose_name='bagian / bidang pekerjaan')),
                ('start_date', models.DateField(blank=True, help_text='Tanggal mulai bekerja.', null=True, verbose_name='tanggal mulai')),
                ('end_date', models.DateField(blank=True, help_text='Tanggal selesai. Kosongkan jika masih bekerja.', null=True, verbose_name='tanggal selesai')),
                ('still_employed', models.BooleanField(default=False, help_text='Centang jika masih bekerja di sini.', verbose_name='masih bekerja')),
                ('description', models.TextField(blank=True, help_text='Deskripsi singkat tugas atau pencapaian.', verbose_name='keterangan')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Urutan tampilan (angka lebih kecil tampil lebih dulu).', verbose_name='urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('applicant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='account.applicantprofile', verbose_name='profil pelamar')),
            ],
            options={
                'verbose_name': 'pengalaman kerja',
                'verbose_name_plural': 'daftar pengalaman kerja',
                'ordering': ['applicant_profile', 'sort_order', '-end_date', '-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='account_cus_role_8abfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['created_at'], name='account_app_created_13bbee_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['verification_status', 'submitted_at'], name='account_app_verific_94077b_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['verification_status', 'created_at'], name='account_app_verific_5336ba_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['referrer', 'verification_status'], name='account_app_referre_75d9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['province', 'verification_status'], name='account_app_provinc_3b21fb_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['district', 'verification_status'], name='account_app_distric_638bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['religion', 'verification_status'], name='account_app_religio_aec601_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['education_level', 'verification_status'], name='account_app_educati_406c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['marital_status', 'verification_status'], name='account_app_marital_c36c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['submitted_at', 'verification_status'], name='account_app_submitt_2646fa_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['verified_at', 'verification_status'], name='account_app_verifie_8cff07_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['verification_status', 'verified_by', 'verified_at'], name='account_app_verific_4b8a49_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['referrer', 'created_at'], name='account_app_referre_3c9cc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicantprofile',
            constraint=models.CheckConstraint(condition=models.Q(('passport_expiry_date__isnull', True), ('passport_issue_date__isnull', True), ('passport_expiry_date__gt', models.F('passport_issue_date')), _connector='OR'), name='passport_expiry_after_issue'),
        ),
        migrations.AddConstraint(
            model_name='applicantprofile',
            constraint=models.CheckConstraint(condition=models.Q(('verification_status', 'DRAFT'), ('submitted_at__isnull', False), _connector='OR'), name='submitted_at_required_after_draft'),
        ),
        migrations.AddConstraint(
            model_name='applicantprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('verification_status__in', ['ACCEPTED', 'REJECTED']), _negated=True), ('verified_at__isnull', False), _connector='OR'), name='verified_at_required_for_final_status'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['user'], name='account_com_user_id_b3231f_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['company_name'], name='account_com_company_903313_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['applicant_profile', 'document_type'], name='account_app_applica_3f5c29_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['uploaded_at'], name='account_app_uploade_7a5ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['review_status'], name='account_app_review__60b56e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['applicant_profile', 'review_status'], name='account_app_applica_d2b066_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['review_status', 'uploaded_at'], name='account_app_review__f00dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['document_type', 'review_status'], name='account_app_documen_dd0878_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicantdocument',
            constraint=models.UniqueConstraint(fields=('applicant_profile', 'document_type'), name='account_applicantdocument_unique_profile_doctype'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['user'], name='account_sta_user_id_b1d166_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['applicant_profile'], name='account_wor_applica_22ef8c_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['applicant_profile', 'sort_order'], name='account_wor_applica_35188c_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['country'], name='account_wor_country_e81b85_idx'),
        ),
    ]
