# Generated by Django 6.0.2 on 2026-02-10 05:26

import account.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, help_text='Digunakan untuk login dan notifikasi.', max_length=254, unique=True, verbose_name='alamat email')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staf'), ('COMPANY', 'Perusahaan'), ('APPLICANT', 'Pelamar')], db_index=True, default='APPLICANT', help_text='Menentukan akses dan profil (staf/pelamar/perusahaan) yang berlaku.', max_length=9, verbose_name='peran')),
                ('email_verified', models.BooleanField(db_index=True, default=False, help_text='Apakah alamat email sudah diverifikasi.', verbose_name='email terverifikasi')),
                ('email_verified_at', models.DateTimeField(blank=True, help_text='Waktu email diverifikasi.', null=True, verbose_name='email terverifikasi pada')),
                ('google_id', models.CharField(blank=True, db_index=True, help_text='ID subjek Google OAuth untuk login sosial.', max_length=255, null=True, unique=True, verbose_name='Google ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'pengguna',
                'verbose_name_plural': 'daftar pengguna',
                'ordering': ['-is_active', 'email'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nama lengkap sesuai dokumen identitas.', max_length=255, verbose_name='nama lengkap CPMI')),
                ('birth_place', models.CharField(blank=True, max_length=255, verbose_name='tempat lahir')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='tanggal lahir')),
                ('address', models.TextField(blank=True, help_text='Alamat sesuai KTP (lengkap sampai Kota/Kabupaten).', verbose_name='alamat sesuai KTP')),
                ('contact_phone', models.CharField(blank=True, help_text='Nomor HP/WA yang aktif.', max_length=50, verbose_name='no. HP / WA yang aktif')),
                ('sibling_count', models.PositiveSmallIntegerField(blank=True, help_text='Jumlah saudara.', null=True, verbose_name='jumlah saudara')),
                ('birth_order', models.PositiveSmallIntegerField(blank=True, help_text='Anak ke- (urutan lahir dalam keluarga).', null=True, verbose_name='anak ke')),
                ('father_name', models.CharField(blank=True, help_text='Nama ayah kandung.', max_length=255, verbose_name='nama ayah')),
                ('father_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='umur ayah')),
                ('father_occupation', models.CharField(blank=True, max_length=255, verbose_name='pekerjaan ayah')),
                ('mother_name', models.CharField(blank=True, help_text='Nama ibu kandung.', max_length=255, verbose_name='nama ibu')),
                ('mother_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='umur ibu')),
                ('mother_occupation', models.CharField(blank=True, max_length=255, verbose_name='pekerjaan ibu')),
                ('spouse_name', models.CharField(blank=True, help_text='Nama suami atau istri (jika sudah menikah).', max_length=255, verbose_name='nama suami / istri')),
                ('spouse_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='umur suami / istri')),
                ('spouse_occupation', models.CharField(blank=True, max_length=255, verbose_name='pekerjaan suami / istri')),
                ('family_address', models.TextField(blank=True, help_text='Alamat orangtua/keluarga (lengkap sampai Kota/Kabupaten).', verbose_name='alamat orangtua / keluarga')),
                ('family_contact_phone', models.CharField(blank=True, help_text='Nomor HP/WA keluarga yang aktif.', max_length=50, verbose_name='no. HP / WA keluarga yang aktif')),
                ('nik', models.CharField(db_index=True, help_text='Nomor Induk Kependudukan (NIK). 16 digit, unik per pelamar. Validasi format (16 digit) di API/serializer.', max_length=16, unique=True, verbose_name='NIK')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Laki-laki'), ('F', 'Perempuan'), ('O', 'Lainnya')], max_length=1, verbose_name='jenis kelamin')),
                ('photo', models.ImageField(blank=True, help_text='Pas photo berwarna background putih ukuran 3x4.', null=True, upload_to='account/applicants/%Y/%m/', verbose_name='pas photo PMI')),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan (III. Keterangan).', verbose_name='keterangan')),
                ('verification_status', models.CharField(choices=[('DRAFT', 'Draf'), ('SUBMITTED', 'Dikirim'), ('ACCEPTED', 'Diterima'), ('REJECTED', 'Ditolak')], db_index=True, default='DRAFT', help_text='Draf: mengisi data. Dikirim: menunggu admin. Diterima/Ditolak: setelah verifikasi.', max_length=9, verbose_name='status verifikasi')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Waktu pelamar mengirim untuk verifikasi (status → Dikirim).', null=True, verbose_name='dikirim pada')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Waktu admin menetapkan status Diterima atau Ditolak.', null=True, verbose_name='diverifikasi pada')),
                ('verification_notes', models.TextField(blank=True, help_text='Catatan internal atau alasan penolakan yang ditampilkan ke pelamar.', verbose_name='catatan verifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('referrer', models.ForeignKey(blank=True, help_text='Staf atau Admin yang merujuk pelamar ini. Jika kosong, dianggap Admin.', limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_applicants', to=settings.AUTH_USER_MODEL, verbose_name='perujuk')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'APPLICANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin atau Staf yang memverifikasi pelamar ini.', limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_applicants', to=settings.AUTH_USER_MODEL, verbose_name='diverifikasi oleh')),
            ],
            options={
                'verbose_name': 'profil pelamar',
                'verbose_name_plural': 'daftar profil pelamar',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Nama perusahaan terdaftar.', max_length=255, verbose_name='nama perusahaan')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='telepon kontak')),
                ('address', models.TextField(blank=True, verbose_name='alamat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'COMPANY'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'profil perusahaan',
                'verbose_name_plural': 'daftar profil perusahaan',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Kode unik (mis. ktp, ijasah, kk).', unique=True, verbose_name='kode')),
                ('name', models.CharField(help_text='Nama tampilan (mis. KTP, Ijasah).', max_length=255, verbose_name='nama')),
                ('is_required', models.BooleanField(default=True, help_text='Apakah dokumen ini wajib untuk pendaftaran/penempatan.', verbose_name='wajib')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Urutan di daftar (angka lebih kecil tampil lebih dulu).', verbose_name='urutan')),
                ('description', models.CharField(blank=True, help_text='Petunjuk opsional (mis. Paspor bagi yang sudah ada).', max_length=500, verbose_name='deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
            ],
            options={
                'verbose_name': 'tipe dokumen',
                'verbose_name_plural': 'daftar tipe dokumen',
                'ordering': ['sort_order', 'code'],
                'indexes': [models.Index(fields=['code'], name='account_doc_code_958aa3_idx'), models.Index(fields=['is_required', 'sort_order'], name='account_doc_is_requ_af3b60_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Berkas dokumen yang diunggah.', upload_to=account.models.applicant_document_upload_to, verbose_name='berkas')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='diunggah pada')),
                ('ocr_text', models.TextField(blank=True, help_text='Teks penuh dari OCR (mis. Google Vision).', verbose_name='teks OCR')),
                ('ocr_data', models.JSONField(blank=True, default=dict, help_text='Data terstruktur dari OCR untuk mengisi biodata. Untuk KTP: nik, nama, tempat_lahir, tanggal_lahir, alamat, jenis_kelamin.', verbose_name='data hasil OCR')),
                ('ocr_processed_at', models.DateTimeField(blank=True, help_text='Waktu ekstraksi OCR terakhir dijalankan untuk dokumen ini.', null=True, verbose_name='diproses OCR pada')),
                ('applicant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='account.applicantprofile', verbose_name='profil pelamar')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_documents', to='account.documenttype', verbose_name='tipe dokumen')),
            ],
            options={
                'verbose_name': 'dokumen pelamar',
                'verbose_name_plural': 'daftar dokumen pelamar',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nama lengkap staf.', max_length=255, verbose_name='nama lengkap')),
                ('contact_phone', models.CharField(blank=True, help_text='Nomor telepon kontak.', max_length=50, verbose_name='telepon kontak')),
                ('photo', models.ImageField(blank=True, help_text='Foto profil staf.', null=True, upload_to='account/staff/%Y/%m/', verbose_name='foto profil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'profil staf',
                'verbose_name_plural': 'daftar profil staf',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Nama perusahaan atau pemberi kerja.', max_length=255, verbose_name='nama perusahaan / pemberi kerja')),
                ('position', models.CharField(blank=True, help_text='Jabatan atau posisi yang diemban.', max_length=255, verbose_name='jabatan / posisi')),
                ('start_date', models.DateField(blank=True, help_text='Tanggal mulai bekerja.', null=True, verbose_name='tanggal mulai')),
                ('end_date', models.DateField(blank=True, help_text='Tanggal selesai. Kosongkan jika masih bekerja.', null=True, verbose_name='tanggal selesai')),
                ('still_employed', models.BooleanField(default=False, help_text='Centang jika masih bekerja di sini.', verbose_name='masih bekerja')),
                ('description', models.TextField(blank=True, help_text='Deskripsi singkat tugas atau pencapaian.', verbose_name='keterangan')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Urutan tampilan (angka lebih kecil tampil lebih dulu).', verbose_name='urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('applicant_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='account.applicantprofile', verbose_name='profil pelamar')),
            ],
            options={
                'verbose_name': 'pengalaman kerja',
                'verbose_name_plural': 'daftar pengalaman kerja',
                'ordering': ['applicant_profile', 'sort_order', '-end_date', '-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='account_cus_role_8abfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['user'], name='account_app_user_id_0b75a0_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['full_name'], name='account_app_full_na_a237fd_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['referrer'], name='account_app_referre_891849_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['verification_status'], name='account_app_verific_d16509_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['created_at'], name='account_app_created_13bbee_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantprofile',
            index=models.Index(fields=['verification_status', 'submitted_at'], name='account_app_verific_94077b_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['user'], name='account_com_user_id_b3231f_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['company_name'], name='account_com_company_903313_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['applicant_profile', 'document_type'], name='account_app_applica_3f5c29_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['uploaded_at'], name='account_app_uploade_7a5ad1_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicantdocument',
            constraint=models.UniqueConstraint(fields=('applicant_profile', 'document_type'), name='account_applicantdocument_unique_profile_doctype'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['user'], name='account_sta_user_id_b1d166_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['applicant_profile'], name='account_wor_applica_22ef8c_idx'),
        ),
        migrations.AddIndex(
            model_name='workexperience',
            index=models.Index(fields=['applicant_profile', 'sort_order'], name='account_wor_applica_35188c_idx'),
        ),
    ]
