# Generated by Django 6.0.2 on 2026-03-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='phase',
            field=models.CharField(choices=[('INITIAL', 'Awal (saat pendaftaran)'), ('POST_INTERVIEW', 'Setelah Lulus Interview')], db_index=True, default='INITIAL', help_text='Kapan dokumen ini diunggah: INITIAL = saat daftar, POST_INTERVIEW = setelah lulus interview.', max_length=20, verbose_name='fase unggah'),
        ),
    ]
