# Generated by Django 6.0.2 on 2026-02-18 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('regions', '0002_rename_regions_district_regency_idx_regions_dis_regency_0a3d69_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='birth_place',
            field=models.ForeignKey(blank=True, help_text='Kabupaten/Kota tempat lahir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_profiles_birth_place', to='regions.regency', verbose_name='tempat lahir'),
        ),
    ]
