# Generated by Django 6.0.2 on 2026-03-05 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_documenttype_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='Waktu pelamar mengirim untuk verifikasi (status → Dikirim).', null=True, verbose_name='dikirim pada'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='verification_status',
            field=models.CharField(choices=[('DRAFT', 'Draf'), ('SUBMITTED', 'Dikirim'), ('ACCEPTED', 'Diterima'), ('REJECTED', 'Ditolak')], db_index=True, default='SUBMITTED', help_text='Draf: mengisi data. Dikirim: menunggu admin. Diterima/Ditolak: setelah verifikasi.', max_length=9, verbose_name='status verifikasi'),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inapp_enabled', models.BooleanField(default=True, help_text='Tampilkan notifikasi di dalam aplikasi.', verbose_name='notifikasi in-app')),
                ('email_account_updates', models.BooleanField(default=True, help_text='Email untuk perubahan kata sandi, keamanan akun.', verbose_name='email perubahan akun')),
                ('email_profile_updates', models.BooleanField(default=True, help_text='Email saat profil diterima atau ditolak oleh admin.', verbose_name='email status verifikasi profil')),
                ('email_application_updates', models.BooleanField(default=True, help_text='Email saat status lamaran kerja berubah (Interview, Diterima, dll.).', verbose_name='email status lamaran')),
                ('email_job_deadline_reminder', models.BooleanField(default=True, help_text='Email pengingat 3 hari sebelum deadline lowongan yang relevan.', verbose_name='email pengingat deadline')),
                ('email_batch_departure_reminder', models.BooleanField(default=True, help_text='Email pengingat 7 hari dan 1 hari sebelum keberangkatan batch.', verbose_name='email pengingat keberangkatan')),
                ('email_job_alerts', models.BooleanField(default=False, help_text='Email saat ada lowongan baru yang dipublikasikan (opt-in).', verbose_name='email lowongan baru')),
                ('push_enabled', models.BooleanField(default=True, help_text='Izinkan push notification ke perangkat.', verbose_name='push notification')),
                ('push_chat_messages', models.BooleanField(default=True, help_text='Push notification untuk pesan chat baru.', verbose_name='push pesan chat')),
                ('push_application_updates', models.BooleanField(default=True, help_text='Push notification saat status lamaran berubah.', verbose_name='push status lamaran')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'preferensi notifikasi',
                'verbose_name_plural': 'preferensi notifikasi',
            },
        ),
    ]
