# Generated by Django 6.0.2 on 2026-02-10 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdocument',
            name='review_notes',
            field=models.TextField(blank=True, help_text='Catatan admin/staff terkait review dokumen (mis. alasan ditolak, catatan khusus).', verbose_name='catatan review'),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Menunggu Review'), ('APPROVED', 'Diterima'), ('REJECTED', 'Ditolak')], db_index=True, default='PENDING', help_text='Status review dokumen oleh admin/staff.', max_length=8, verbose_name='status review'),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Waktu dokumen direview (APPROVED atau REJECTED).', null=True, verbose_name='direview pada'),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin atau Staff yang mereview dokumen ini.', limit_choices_to={'role__in': ['STAFF', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='direview oleh'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['review_status'], name='account_app_review__60b56e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantdocument',
            index=models.Index(fields=['applicant_profile', 'review_status'], name='account_app_applica_d2b066_idx'),
        ),
    ]
