# Generated by Django 6.0.2 on 2026-02-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_applicantprofile_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='score',
            field=models.FloatField(blank=True, db_index=True, help_text='Skor kesiapan pelamar (0-100) berdasarkan kelengkapan biodata dan dokumen.', null=True, verbose_name='skor kesiapan'),
        ),
    ]
