# Generated by Django 6.0.2 on 2026-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_applicantprofile_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='bank',
            field=models.CharField(blank=True, help_text='Nama bank tujuan pengembalian/transfer.', max_length=100, verbose_name='bank'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='biaya_ready_paspor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Biaya yang dikeluarkan untuk ready paspor (dalam Rupiah).', max_digits=12, null=True, verbose_name='biaya ready paspor'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='disnaker',
            field=models.CharField(blank=True, help_text='Informasi Disnaker terkait pelamar (jika ada).', max_length=255, verbose_name='disnaker'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='hasil_medical',
            field=models.CharField(blank=True, help_text='Ringkasan hasil medical (FIT/UNFIT atau catatan singkat).', max_length=255, verbose_name='hasil medical'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='jlh_uang_transport',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total uang transport (dalam Rupiah).', max_digits=12, null=True, verbose_name='jumlah uang transport'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='no_calling_visa',
            field=models.CharField(blank=True, help_text='Nomor calling visa.', max_length=100, verbose_name='nomor calling visa'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='no_id_sisko',
            field=models.CharField(blank=True, help_text='Nomor ID SISKO pelamar.', max_length=100, verbose_name='nomor ID SISKO'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='no_jo',
            field=models.CharField(blank=True, help_text='Nomor JO.', max_length=100, verbose_name='nomor JO'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='no_rek',
            field=models.CharField(blank=True, help_text='Nomor rekening tujuan.', max_length=100, verbose_name='nomor rekening'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='no_sip',
            field=models.CharField(blank=True, help_text='Nomor SIP.', max_length=100, verbose_name='nomor SIP'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='pengembalian_biaya',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Jumlah biaya yang dikembalikan (dalam Rupiah).', max_digits=12, null=True, verbose_name='pengembalian biaya'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tanggal_pengembalian',
            field=models.DateField(blank=True, help_text='Tanggal pengembalian dana ditransfer.', null=True, verbose_name='tanggal pengembalian (transfer)'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tgl_bayar_bpjs_pra',
            field=models.DateField(blank=True, help_text='Tanggal pembayaran BPJS pra penempatan.', null=True, verbose_name='tanggal bayar BPJS pra'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tgl_bayar_bpjs_purna',
            field=models.DateField(blank=True, help_text='Tanggal pembayaran BPJS purna.', null=True, verbose_name='tanggal bayar BPJS purna'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tgl_bayar_psikotes',
            field=models.DateField(blank=True, help_text='Tanggal pembayaran biaya psikotes.', null=True, verbose_name='tanggal bayar psikotes'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tgl_bayar_sml',
            field=models.DateField(blank=True, help_text='Tanggal pembayaran ke SML.', null=True, verbose_name='tanggal bayar SML'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tgl_calling_visa',
            field=models.DateField(blank=True, help_text='Tanggal calling visa diterbitkan.', null=True, verbose_name='tanggal calling visa'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tgl_fwcm_psikotes',
            field=models.DateField(blank=True, help_text='Tanggal FWCMS dan psikotes dilakukan.', null=True, verbose_name='tanggal FWCMS & psikotes'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tgl_kirim_bio_ke_mly',
            field=models.DateField(blank=True, help_text='Tanggal biodata dikirim ke Malaysia.', null=True, verbose_name='tanggal kirim biodata ke Malaysia'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tgl_medical',
            field=models.DateField(blank=True, help_text='Tanggal pemeriksaan medical.', null=True, verbose_name='tanggal medical'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tgl_pengembalian',
            field=models.DateField(blank=True, help_text='Tanggal pengembalian biaya dilakukan.', null=True, verbose_name='tanggal pengembalian biaya'),
        ),
    ]
