# Generated by Django 6.0.2 on 2026-02-20 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_applicantprofile_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul notifikasi yang akan ditampilkan.', max_length=255, verbose_name='judul')),
                ('message', models.TextField(help_text='Isi pesan notifikasi.', verbose_name='pesan')),
                ('notification_type', models.CharField(choices=[('INFO', 'Informasi'), ('SUCCESS', 'Sukses'), ('WARNING', 'Peringatan'), ('ERROR', 'Error'), ('BROADCAST', 'Broadcast')], db_index=True, default='INFO', max_length=20, verbose_name='tipe')),
                ('priority', models.CharField(choices=[('LOW', 'Rendah'), ('NORMAL', 'Normal'), ('HIGH', 'Tinggi'), ('URGENT', 'Mendesak')], db_index=True, default='NORMAL', max_length=10, verbose_name='prioritas')),
                ('recipient_config', models.JSONField(default=dict, help_text='Konfigurasi untuk memilih penerima: roles, filters, user_ids, etc.', verbose_name='konfigurasi penerima')),
                ('send_email', models.BooleanField(default=False, help_text='Kirim notifikasi via email juga.', verbose_name='kirim email')),
                ('send_in_app', models.BooleanField(default=True, help_text='Tampilkan notifikasi di aplikasi.', verbose_name='kirim in-app')),
                ('send_push', models.BooleanField(default=False, help_text='Kirim notifikasi push ke perangkat (web/mobile).', verbose_name='kirim push notification')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Jadwalkan pengiriman untuk waktu tertentu (null = kirim sekarang).', null=True, verbose_name='dijadwalkan pada')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Waktu ketika broadcast dikirim.', null=True, verbose_name='dikirim pada')),
                ('total_recipients', models.PositiveIntegerField(default=0, help_text='Jumlah total penerima yang menerima notifikasi ini.', verbose_name='total penerima')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh')),
            ],
            options={
                'verbose_name': 'broadcast',
                'verbose_name_plural': 'broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Firebase Cloud Messaging token.', max_length=255, unique=True, verbose_name='FCM token')),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], db_index=True, default='web', max_length=20, verbose_name='tipe perangkat')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Token masih valid dan dapat menerima notifikasi.', verbose_name='aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='dibuat pada')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='terakhir digunakan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'device token',
                'verbose_name_plural': 'device tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='judul')),
                ('message', models.TextField(verbose_name='pesan')),
                ('notification_type', models.CharField(choices=[('INFO', 'Informasi'), ('SUCCESS', 'Sukses'), ('WARNING', 'Peringatan'), ('ERROR', 'Error'), ('BROADCAST', 'Broadcast')], db_index=True, default='INFO', max_length=20, verbose_name='tipe')),
                ('priority', models.CharField(choices=[('LOW', 'Rendah'), ('NORMAL', 'Normal'), ('HIGH', 'Tinggi'), ('URGENT', 'Mendesak')], db_index=True, default='NORMAL', max_length=10, verbose_name='prioritas')),
                ('action_url', models.URLField(blank=True, help_text='URL untuk link/aksi di notifikasi (opsional).', null=True, verbose_name='URL aksi')),
                ('action_label', models.CharField(blank=True, help_text='Label untuk tombol aksi (opsional).', max_length=100, verbose_name='label aksi')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='sudah dibaca')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='dibaca pada')),
                ('email_sent', models.BooleanField(default=False, verbose_name='email terkirim')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='email terkirim pada')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='dibuat pada')),
                ('broadcast', models.ForeignKey(blank=True, help_text='Broadcast yang menghasilkan notifikasi ini (null jika standalone).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.broadcast', verbose_name='broadcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'notifikasi',
                'verbose_name_plural': 'notifikasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['created_by', 'created_at'], name='account_bro_created_8d5c65_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['scheduled_at', 'sent_at'], name='account_bro_schedul_c997f4_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user', 'is_active'], name='account_dev_user_id_d5e560_idx'),
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['token'], name='account_dev_token_50e66e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='account_not_user_id_e1a5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='account_not_user_id_18fc9d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['broadcast', 'created_at'], name='account_not_broadca_be9675_idx'),
        ),
    ]
