# Generated by Django 6.0.2 on 2026-03-09 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_applicantprofile_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Alasan penghapusan akun (opsional, diisi oleh pengguna).', verbose_name='alasan')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Konfirmasi'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('CANCELLED', 'Dibatalkan')], db_index=True, default='PENDING', max_length=9, verbose_name='status')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='diminta pada')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Waktu admin meninjau permintaan ini.', null=True, verbose_name='ditinjau pada')),
                ('admin_notes', models.TextField(blank=True, help_text='Catatan internal admin (alasan penolakan, catatan khusus).', verbose_name='catatan admin')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin yang menyetujui atau menolak permintaan.', limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletion_requests', to=settings.AUTH_USER_MODEL, verbose_name='ditinjau oleh')),
                ('user', models.OneToOneField(help_text='Pengguna yang mengajukan penghapusan akun.', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_request', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'permintaan penghapusan akun',
                'verbose_name_plural': 'permintaan penghapusan akun',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='account_acc_status_e47e60_idx')],
            },
        ),
    ]
