# Generated by Django 6.0.2 on 2026-02-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_broadcast_devicetoken_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='heir_contact_phone',
            field=models.CharField(blank=True, help_text='Nomor HP atau WhatsApp ahli waris yang aktif.', max_length=50, verbose_name='no. HP / WA ahli waris'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='heir_name',
            field=models.CharField(blank=True, help_text='Nama lengkap ahli waris.', max_length=255, verbose_name='nama ahli waris'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='heir_relationship',
            field=models.CharField(blank=True, choices=[('SUAMI', 'Suami'), ('ISTRI', 'Istri'), ('AYAH', 'Ayah'), ('IBU', 'Ibu'), ('KAKAK', 'Kakak'), ('ADIK', 'Adik'), ('ANAK', 'Anak'), ('PAMAN', 'Paman'), ('BIBI', 'Bibi'), ('LAINNYA', 'Lainnya')], help_text='Hubungan ahli waris dengan pelamar (mis. Suami, Istri, Ayah, Ibu).', max_length=7, verbose_name='hubungan ahli waris'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='register_number',
            field=models.CharField(blank=True, db_index=True, help_text='Nomor register unik pelamar (contoh: AP2026000001). Di-generate otomatis saat pertama kali disimpan.', max_length=20, null=True, unique=True, verbose_name='nomor register pelamar'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_person_name',
            field=models.CharField(blank=True, help_text='Nama lengkap orang yang dapat dihubungi di perusahaan.', max_length=255, verbose_name='nama contact person'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_person_position',
            field=models.CharField(blank=True, help_text='Jabatan atau posisi contact person di perusahaan.', max_length=255, verbose_name='jabatan contact person'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Alamat lengkap staf sesuai KTP.', verbose_name='alamat'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='nik',
            field=models.CharField(blank=True, help_text='Nomor Induk Kependudukan staf (16 digit).', max_length=16, verbose_name='NIK staf'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Nomor HP atau WhatsApp contact person yang aktif.', max_length=50, verbose_name='no. HP / WA contact person'),
        ),
    ]
