# Generated by Django 6.0.2 on 2026-03-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_applicantprofile_heir_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='send_push',
            field=models.BooleanField(default=True, help_text='Kirim notifikasi push ke perangkat (web/mobile).', verbose_name='kirim push notification'),
        ),
    ]
