# Generated by Django 6.0.2 on 2026-04-06 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_accountdeletionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdeletionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin yang menyetujui atau menolak permintaan.', limit_choices_to={'role__in': ['MASTER_ADMIN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletion_requests', to=settings.AUTH_USER_MODEL, verbose_name='ditinjau oleh'),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin atau Staff yang mereview dokumen ini.', limit_choices_to={'role__in': ['STAFF', 'MASTER_ADMIN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='direview oleh'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='referrer',
            field=models.ForeignKey(blank=True, help_text='Staf atau Admin yang merujuk pelamar ini. Jika kosong, dianggap Admin.', limit_choices_to={'role__in': ['STAFF', 'MASTER_ADMIN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_applicants', to=settings.AUTH_USER_MODEL, verbose_name='perujuk'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin atau Staf yang memverifikasi pelamar ini.', limit_choices_to={'role__in': ['STAFF', 'MASTER_ADMIN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_applicants', to=settings.AUTH_USER_MODEL, verbose_name='diverifikasi oleh'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MASTER_ADMIN', 'ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Admin Utama'), ('ADMIN', 'Admin'), ('STAFF', 'Staf'), ('COMPANY', 'Perusahaan'), ('APPLICANT', 'Pelamar')], db_index=True, default='APPLICANT', help_text='Menentukan akses dan profil (staf/pelamar/perusahaan) yang berlaku.', max_length=12, verbose_name='peran'),
        ),
    ]
