# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_accountdeletionrequest_reviewed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantprofile",
            name="father_almarhum",
            field=models.BooleanField(
                default=False,
                help_text="Centang jika ayah kandung sudah meninggal.",
                verbose_name="ayah almarhum",
            ),
        ),
        migrations.AddField(
            model_name="applicantprofile",
            name="mother_almarhum",
            field=models.BooleanField(
                default=False,
                help_text="Centang jika ibu kandung sudah meninggal (Almarhumah).",
                verbose_name="ibu almarhumah",
            ),
        ),
    ]
