# Generated by Django 6.0.2 on 2026-03-03 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_broadcast_send_push'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='6-digit kode verifikasi email.', max_length=6, verbose_name='kode verifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Waktu kedaluwarsa kode.', verbose_name='kedaluwarsa pada')),
                ('is_used', models.BooleanField(default=False, help_text='Kode sudah diverifikasi.', verbose_name='sudah digunakan')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Jumlah percobaan verifikasi gagal.', verbose_name='percobaan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='pengguna')),
            ],
            options={
                'verbose_name': 'kode verifikasi email',
                'verbose_name_plural': 'kode verifikasi email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='account_ema_user_id_de7b13_idx'), models.Index(fields=['code', 'is_used'], name='account_ema_code_e3ae4b_idx')],
            },
        ),
    ]
