# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_applicantprofile_father_almarhum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantprofile",
            name="spouse_almarhum",
            field=models.BooleanField(
                default=False,
                help_text="Centang jika pasangan (suami/istri) sudah meninggal.",
                verbose_name="suami / istri almarhum",
            ),
        ),
    ]
