# Generated by Django 6.0.2 on 2026-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_emailverificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='family_contact_phone',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='father_phone',
            field=models.CharField(blank=True, help_text='Nomor HP/WA ayah yang aktif.', max_length=50, verbose_name='no. HP / WA ayah'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_phone',
            field=models.CharField(blank=True, help_text='Nomor HP/WA ibu yang aktif.', max_length=50, verbose_name='no. HP / WA ibu'),
        ),
    ]
