# Generated by Django 6.0.2 on 2026-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_applicantprofile_spouse_almarhum'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apple_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID subjek Apple Sign-In untuk login sosial.', max_length=255, null=True, unique=True, verbose_name='Apple ID'),
        ),
    ]
