# Generated by Django 6.0.2 on 2026-04-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_add_apple_id_to_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_account_updates',
            field=models.BooleanField(default=False, help_text='Email untuk perubahan kata sandi, keamanan akun.', verbose_name='email perubahan akun'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_application_updates',
            field=models.BooleanField(default=False, help_text='Email saat status lamaran kerja berubah (Interview, Diterima, dll.).', verbose_name='email status lamaran'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_batch_departure_reminder',
            field=models.BooleanField(default=False, help_text='Email pengingat 7 hari dan 1 hari sebelum keberangkatan batch.', verbose_name='email pengingat keberangkatan'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_job_deadline_reminder',
            field=models.BooleanField(default=False, help_text='Email pengingat 3 hari sebelum deadline lowongan yang relevan.', verbose_name='email pengingat deadline'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_profile_updates',
            field=models.BooleanField(default=False, help_text='Email saat profil diterima atau ditolak oleh admin.', verbose_name='email status verifikasi profil'),
        ),
    ]
