# Generated by Django 6.0.2 on 2026-04-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_applicantprofile_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='destination_country',
            field=models.CharField(blank=True, choices=[('MALAYSIA', 'Malaysia')], default='MALAYSIA', help_text='Negara tujuan penempatan.', max_length=20, verbose_name='negara yang dituju'),
        ),
    ]
