# Generated by Django 6.0.2 on 2026-05-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_applicant_verification_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantInboundTransportStageCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_code', models.CharField(choices=[('MASUK_BERKAS_ASLI', 'Masuk Berkas Asli'), ('MEDICAL', 'Medical'), ('BUAT_ID_PEKERJA', 'Buat ID Pekerja'), ('BUAT_PASPOR', 'Buat Paspor'), ('FWCMS', 'FWCMS'), ('PSIKOLOGI_TEST', 'Psikologi Test'), ('PAP_BP3MI', 'PAP BP3MI'), ('PDO_KILANG', 'PDO Kilang'), ('PERSIAPAN_KEBERANGKATAN', 'Persiapan Keberangkatan')], db_index=True, max_length=30, verbose_name='kode sub-tahapan')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='jumlah (Rp)')),
                ('keterangan', models.CharField(blank=True, max_length=500, verbose_name='keterangan')),
                ('tanggal_proses', models.DateField(blank=True, null=True, verbose_name='tanggal proses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_transport_stage_costs', to='account.applicantprofile', verbose_name='profil pelamar')),
            ],
            options={
                'verbose_name': 'biaya transport inbound per tahap',
                'verbose_name_plural': 'biaya transport inbound per tahap',
                'indexes': [models.Index(fields=['profile', 'stage_code'], name='account_app_profile_265c87_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'stage_code'), name='uniq_applicant_inbound_transport_stage')],
            },
        ),
    ]
