# ===========================================================================
# KMS Connect — ProGuard / R8 Rules
# ===========================================================================
# Generated for: Flutter + Firebase + Google Sign-In + Dio + Hive +
#                flutter_secure_storage + Riverpod + freezed + go_router
# ===========================================================================


# ---------------------------------------------------------------------------
# Flutter — keep all engine classes
# ---------------------------------------------------------------------------
-keep class io.flutter.** { *; }
-keep class io.flutter.embedding.** { *; }
-dontwarn io.flutter.embedding.**


# ---------------------------------------------------------------------------
# Firebase Core & Messaging
# ---------------------------------------------------------------------------
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.firebase.**
-dontwarn com.google.android.gms.**

# FCM token & notification handling
-keep class com.google.firebase.messaging.** { *; }
-keep class com.google.firebase.installations.** { *; }


# ---------------------------------------------------------------------------
# Google Sign-In
# ---------------------------------------------------------------------------
-keep class com.google.android.gms.auth.** { *; }
-keep class com.google.android.gms.common.** { *; }
-keep class com.google.android.gms.tasks.** { *; }


# ---------------------------------------------------------------------------
# Dio & OkHttp (HTTP client)
# ---------------------------------------------------------------------------
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-keepattributes Signature
-keepattributes *Annotation*


# ---------------------------------------------------------------------------
# Hive (local cache for dio_cache_interceptor_hive_store)
# ---------------------------------------------------------------------------
-keep class com.hive.** { *; }
-keep class io.hive.** { *; }
# Hive TypeAdapters generated by hive_generator
-keep class **$HiveFieldAdapter { *; }


# ---------------------------------------------------------------------------
# flutter_secure_storage
# ---------------------------------------------------------------------------
-keep class com.it_nomads.fluttersecurestorage.** { *; }


# ---------------------------------------------------------------------------
# flutter_local_notifications
# ---------------------------------------------------------------------------
-keep class com.dexterous.flutterlocalnotifications.** { *; }


# ---------------------------------------------------------------------------
# image_picker / image_cropper / camera
# ---------------------------------------------------------------------------
-keep class io.flutter.plugins.imagepicker.** { *; }
-keep class com.yalantis.ucrop.** { *; }
-keep interface com.yalantis.ucrop.** { *; }


# ---------------------------------------------------------------------------
# file_picker
# ---------------------------------------------------------------------------
-keep class com.mr.flutter.plugin.filepicker.** { *; }


# ---------------------------------------------------------------------------
# permission_handler
# ---------------------------------------------------------------------------
-keep class com.baseflow.permissionhandler.** { *; }


# ---------------------------------------------------------------------------
# connectivity_plus
# ---------------------------------------------------------------------------
-keep class dev.fluttercommunity.plus.connectivity.** { *; }


# ---------------------------------------------------------------------------
# open_filex
# ---------------------------------------------------------------------------
-keep class com.crazecoder.openfile.** { *; }


# ---------------------------------------------------------------------------
# Kotlin coroutines & serialization (used internally by many libs)
# ---------------------------------------------------------------------------
-keep class kotlinx.coroutines.** { *; }
-dontwarn kotlinx.coroutines.**
-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}


# ---------------------------------------------------------------------------
# Freezed / json_serializable generated code
# Keeps the fromJson factory method that R8 would otherwise strip
# ---------------------------------------------------------------------------
-keepclassmembers class * {
    @com.google.gson.annotations.SerializedName <fields>;
}
-keepattributes EnclosingMethod
-keepattributes InnerClasses


# ---------------------------------------------------------------------------
# Prevent stripping BuildConfig (sometimes needed by plugins)
# ---------------------------------------------------------------------------
-keep class **.BuildConfig { *; }


# ---------------------------------------------------------------------------
# Mapping file — uploaded to Play Console for readable crash reports
# ---------------------------------------------------------------------------
-printmapping build/outputs/mapping/release/mapping.txt
