# Generated by Django 6.0.2 on 2026-03-05 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LowonganKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nama posisi atau judul lowongan.', max_length=255, verbose_name='judul lowongan')),
                ('slug', models.SlugField(help_text='Slug unik untuk URL lowongan.', max_length=255, unique=True, verbose_name='slug')),
                ('location_country', models.CharField(blank=True, help_text='Negara tempat kerja (mis. Taiwan, Hong Kong).', max_length=100, verbose_name='negara penempatan')),
                ('location_city', models.CharField(blank=True, help_text='Kota atau area penempatan (opsional).', max_length=100, verbose_name='kota / area')),
                ('description', models.TextField(help_text='Deskripsi tugas utama dan tanggung jawab.', verbose_name='deskripsi pekerjaan')),
                ('requirements', models.TextField(blank=True, help_text='Syarat kualifikasi, pengalaman, dan dokumen khusus.', verbose_name='persyaratan')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Penuh waktu'), ('PART_TIME', 'Paruh waktu'), ('CONTRACT', 'Kontrak'), ('INTERNSHIP', 'Magang')], db_index=True, default='FULL_TIME', max_length=20, verbose_name='jenis kerja')),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Perkiraan gaji minimum (dalam satuan mata uang yang sama).', null=True, verbose_name='gaji minimum')),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Perkiraan gaji maksimum (opsional).', null=True, verbose_name='gaji maksimum')),
                ('currency', models.CharField(default='IDR', help_text='Kode mata uang (mis. IDR, TWD, HKD).', max_length=10, verbose_name='mata uang')),
                ('status', models.CharField(choices=[('DRAFT', 'Draf'), ('OPEN', 'Dibuka'), ('CLOSED', 'Ditutup'), ('ARCHIVED', 'Diarsipkan')], db_index=True, default='DRAFT', max_length=10, verbose_name='status')),
                ('posted_at', models.DateTimeField(blank=True, help_text='Waktu lowongan mulai ditayangkan ke publik.', null=True, verbose_name='diposting pada')),
                ('deadline', models.DateTimeField(blank=True, help_text='Tanggal/waktu terakhir penerimaan lamaran (opsional).', null=True, verbose_name='batas akhir lamaran')),
                ('start_date', models.DateField(blank=True, help_text='Target tanggal pelamar mulai bekerja. Digunakan sebagai informasi bagi pelamar dan admin.', null=True, verbose_name='tanggal mulai kerja')),
                ('quota', models.PositiveSmallIntegerField(blank=True, help_text='Jumlah maksimum pelamar yang diterima untuk lowongan ini. Kosongkan jika tidak ada batasan.', null=True, verbose_name='kuota pelamar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('company', models.ForeignKey(help_text='Perusahaan yang membuka lowongan.', on_delete=django.db.models.deletion.PROTECT, related_name='job_listings', to='account.companyprofile', verbose_name='perusahaan')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/Staf/Perusahaan yang membuat lowongan ini.', limit_choices_to={'role__in': ['ADMIN', 'STAFF', 'COMPANY']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_listings_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh')),
            ],
            options={
                'verbose_name': 'lowongan kerja',
                'verbose_name_plural': 'daftar lowongan kerja',
                'ordering': ['-posted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LamaranBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nama identifikasi batch, misal: 'Batch Maret 2026'.", max_length=100, verbose_name='nama batch')),
                ('notes', models.TextField(blank=True, help_text='Catatan internal admin mengenai batch ini.', verbose_name='catatan')),
                ('pra_seleksi_date', models.DateTimeField(blank=True, db_index=True, help_text='Tanggal dan jam pelaksanaan tahap pra-seleksi.', null=True, verbose_name='tanggal & jam pra-seleksi')),
                ('pra_seleksi_location', models.CharField(blank=True, help_text='Lokasi atau link (online/offline) pelaksanaan pra-seleksi.', max_length=255, verbose_name='lokasi pra-seleksi')),
                ('pra_seleksi_notes', models.TextField(blank=True, help_text='Instruksi atau informasi tambahan untuk pelamar mengenai pra-seleksi.', verbose_name='info pra-seleksi')),
                ('interview_date', models.DateTimeField(blank=True, db_index=True, help_text='Tanggal dan jam pelaksanaan tahap interview.', null=True, verbose_name='tanggal & jam interview')),
                ('interview_location', models.CharField(blank=True, help_text='Lokasi atau link (online/offline) pelaksanaan interview.', max_length=255, verbose_name='lokasi interview')),
                ('interview_notes', models.TextField(blank=True, help_text='Instruksi atau informasi tambahan untuk pelamar mengenai interview.', verbose_name='info interview')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/Staf yang membuat batch ini.', limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh')),
                ('job', models.ForeignKey(help_text='Lowongan kerja yang menjadi target batch ini.', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='main.lowongankerja', verbose_name='lowongan')),
            ],
            options={
                'verbose_name': 'batch lamaran',
                'verbose_name_plural': 'daftar batch lamaran',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRA_SELEKSI', 'Tahap Pra-Seleksi'), ('INTERVIEW', 'Tahap Interview'), ('DITERIMA', 'Tahap Diterima'), ('DITOLAK', 'Tahap Ditolak'), ('BERANGKAT', 'Tahap Berangkat'), ('SELESAI', 'Tahap Selesai')], db_index=True, default='PRA_SELEKSI', help_text='Status tahap lamaran saat ini.', max_length=15, verbose_name='status')),
                ('pra_seleksi_confirmed_at', models.DateTimeField(blank=True, help_text='Waktu pelamar mengkonfirmasi kehadiran di tahap pra-seleksi. Null berarti belum dikonfirmasi.', null=True, verbose_name='konfirmasi pra-seleksi pada')),
                ('interview_confirmed_at', models.DateTimeField(blank=True, help_text='Waktu pelamar mengkonfirmasi kehadiran di tahap interview. Null berarti belum dikonfirmasi.', null=True, verbose_name='konfirmasi interview pada')),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Waktu admin memasukkan pelamar ke batch ini.', verbose_name='ditugaskan pada')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Waktu terakhir status diubah oleh admin/staff.', null=True, verbose_name='direview pada')),
                ('placement_end_date', models.DateField(blank=True, db_index=True, help_text='Tanggal pelamar selesai bekerja. Diisi saat status berubah ke SELESAI. Cooldown 2 tahun dihitung dari tanggal ini.', null=True, verbose_name='tanggal selesai kerja')),
                ('notes', models.TextField(blank=True, help_text='Catatan internal atau feedback untuk pelamar.', verbose_name='catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('applicant', models.ForeignKey(help_text='Pelamar yang terdaftar dalam batch lamaran ini.', on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='account.applicantprofile', verbose_name='pelamar')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin atau Staff yang memasukkan pelamar ke batch ini.', limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='ditugaskan oleh')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin atau Staff yang terakhir mengubah status lamaran ini.', limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='direview oleh')),
                ('batch', models.ForeignKey(blank=True, help_text='Batch lamaran tempat pelamar ini terdaftar.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.lamaranbatch', verbose_name='batch')),
                ('job', models.ForeignKey(help_text='Lowongan kerja yang dilamar (denormalized dari batch untuk query efisien).', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.lowongankerja', verbose_name='lowongan')),
            ],
            options={
                'verbose_name': 'lamaran kerja',
                'verbose_name_plural': 'daftar lamaran kerja',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul singkat berita.', max_length=255, verbose_name='judul')),
                ('slug', models.SlugField(help_text='Slug unik untuk URL berita.', max_length=255, unique=True, verbose_name='slug')),
                ('summary', models.CharField(blank=True, help_text='Ringkasan singkat yang tampil di daftar berita.', max_length=500, verbose_name='ringkasan')),
                ('content', models.TextField(help_text='Konten lengkap berita (teks HTML/markdown yang sudah diformat).', verbose_name='isi berita')),
                ('hero_image', models.ImageField(blank=True, help_text='Gambar utama opsional untuk ditampilkan di halaman detail berita.', null=True, upload_to='main/news/%Y/%m/', verbose_name='gambar utama')),
                ('status', models.CharField(choices=[('DRAFT', 'Draf'), ('PUBLISHED', 'Dipublikasikan'), ('ARCHIVED', 'Diarsipkan')], db_index=True, default='DRAFT', max_length=10, verbose_name='status')),
                ('is_pinned', models.BooleanField(default=False, help_text='Jika dicentang, berita akan muncul di bagian atas daftar.', verbose_name='sematkan di atas')),
                ('published_at', models.DateTimeField(blank=True, help_text='Waktu ketika berita dipublikasikan.', null=True, verbose_name='dipublikasikan pada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/Staf yang membuat berita ini.', limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh')),
            ],
            options={
                'verbose_name': 'berita',
                'verbose_name_plural': 'daftar berita',
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, help_text='Status sebelum perubahan. Kosong jika ini entri awal pembuatan.', max_length=15, verbose_name='dari status')),
                ('to_status', models.CharField(choices=[('PRA_SELEKSI', 'Tahap Pra-Seleksi'), ('INTERVIEW', 'Tahap Interview'), ('DITERIMA', 'Tahap Diterima'), ('DITOLAK', 'Tahap Ditolak'), ('BERANGKAT', 'Tahap Berangkat'), ('SELESAI', 'Tahap Selesai')], help_text='Status setelah perubahan.', max_length=15, verbose_name='ke status')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='diubah pada')),
                ('note', models.TextField(blank=True, verbose_name='catatan')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='diubah oleh')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='main.jobapplication', verbose_name='lamaran')),
            ],
            options={
                'verbose_name': 'riwayat status lamaran',
                'verbose_name_plural': 'riwayat status lamaran',
                'ordering': ['changed_at'],
                'indexes': [models.Index(fields=['application', 'changed_at'], name='main_applic_applica_208e0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='BatchAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Judul singkat pengumuman, misal: 'Jadwal Pra-Seleksi Diperbarui'.", max_length=200, verbose_name='judul')),
                ('body', models.TextField(help_text='Isi lengkap pengumuman yang akan dibaca oleh pelamar.', verbose_name='isi pesan')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='dibuat pada')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh')),
                ('batch', models.ForeignKey(help_text='Batch penerima pengumuman ini.', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='main.lamaranbatch', verbose_name='batch')),
            ],
            options={
                'verbose_name': 'pengumuman batch',
                'verbose_name_plural': 'daftar pengumuman batch',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', 'created_at'], name='main_batcha_batch_i_dd6a92_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lowongankerja',
            index=models.Index(fields=['status', 'employment_type'], name='main_lowong_status_14bce0_idx'),
        ),
        migrations.AddIndex(
            model_name='lowongankerja',
            index=models.Index(fields=['company', 'status'], name='main_lowong_company_ae23e7_idx'),
        ),
        migrations.AddIndex(
            model_name='lowongankerja',
            index=models.Index(fields=['deadline'], name='main_lowong_deadlin_cbb429_idx'),
        ),
        migrations.AddIndex(
            model_name='lowongankerja',
            index=models.Index(fields=['start_date'], name='main_lowong_start_d_b8f346_idx'),
        ),
        migrations.AddIndex(
            model_name='lamaranbatch',
            index=models.Index(fields=['job', 'created_at'], name='main_lamara_job_id_d0e911_idx'),
        ),
        migrations.AddIndex(
            model_name='lamaranbatch',
            index=models.Index(fields=['pra_seleksi_date'], name='main_lamara_pra_sel_c6d029_idx'),
        ),
        migrations.AddIndex(
            model_name='lamaranbatch',
            index=models.Index(fields=['interview_date'], name='main_lamara_intervi_8610a1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'status'], name='main_jobapp_applica_da4d85_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='main_jobapp_job_id_9e39f8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['batch', 'status'], name='main_jobapp_batch_i_b301b3_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', 'applied_at'], name='main_jobapp_status_6cb2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'status', 'job'], name='main_jobapp_applica_c539be_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'status', 'placement_end_date'], name='main_jobapp_applica_8890d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PRA_SELEKSI', 'INTERVIEW', 'DITERIMA', 'BERANGKAT'])), fields=('applicant', 'job'), name='unique_active_application_per_applicant_job'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status', 'published_at'], name='main_news_status_aa97fe_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_pinned', 'status'], name='main_news_is_pinn_ff65df_idx'),
        ),
    ]
