# Generated by Django 6.0.2 on 2026-02-18 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LowonganKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nama posisi atau judul lowongan.', max_length=255, verbose_name='judul lowongan')),
                ('slug', models.SlugField(help_text='Slug unik untuk URL lowongan.', max_length=255, unique=True, verbose_name='slug')),
                ('location_country', models.CharField(blank=True, help_text='Negara tempat kerja (mis. Taiwan, Hong Kong).', max_length=100, verbose_name='negara penempatan')),
                ('location_city', models.CharField(blank=True, help_text='Kota atau area penempatan (opsional).', max_length=100, verbose_name='kota / area')),
                ('description', models.TextField(help_text='Deskripsi tugas utama dan tanggung jawab.', verbose_name='deskripsi pekerjaan')),
                ('requirements', models.TextField(blank=True, help_text='Syarat kualifikasi, pengalaman, dan dokumen khusus.', verbose_name='persyaratan')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Penuh waktu'), ('PART_TIME', 'Paruh waktu'), ('CONTRACT', 'Kontrak'), ('INTERNSHIP', 'Magang')], db_index=True, default='FULL_TIME', max_length=20, verbose_name='jenis kerja')),
                ('salary_min', models.PositiveIntegerField(blank=True, help_text='Perkiraan gaji minimum (dalam satuan mata uang yang sama).', null=True, verbose_name='gaji minimum')),
                ('salary_max', models.PositiveIntegerField(blank=True, help_text='Perkiraan gaji maksimum (opsional).', null=True, verbose_name='gaji maksimum')),
                ('currency', models.CharField(default='IDR', help_text='Kode mata uang (mis. IDR, TWD, HKD).', max_length=10, verbose_name='mata uang')),
                ('status', models.CharField(choices=[('DRAFT', 'Draf'), ('OPEN', 'Dibuka'), ('CLOSED', 'Ditutup'), ('ARCHIVED', 'Diarsipkan')], db_index=True, default='DRAFT', max_length=10, verbose_name='status')),
                ('posted_at', models.DateTimeField(blank=True, help_text='Waktu lowongan mulai ditayangkan ke publik.', null=True, verbose_name='diposting pada')),
                ('deadline', models.DateTimeField(blank=True, help_text='Tanggal/waktu terakhir penerimaan lamaran (opsional).', null=True, verbose_name='batas akhir lamaran')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('company', models.ForeignKey(help_text='Perusahaan yang membuka lowongan.', on_delete=django.db.models.deletion.PROTECT, related_name='job_listings', to='account.companyprofile', verbose_name='perusahaan')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/Staf/Perusahaan yang membuat lowongan ini.', limit_choices_to={'role__in': ['ADMIN', 'STAFF', 'COMPANY']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_listings_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh')),
            ],
            options={
                'verbose_name': 'lowongan kerja',
                'verbose_name_plural': 'daftar lowongan kerja',
                'ordering': ['-posted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Dilamar'), ('UNDER_REVIEW', 'Dalam Review'), ('ACCEPTED', 'Diterima'), ('REJECTED', 'Ditolak')], db_index=True, default='APPLIED', help_text='Status lamaran kerja.', max_length=20, verbose_name='status')),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Waktu pelamar mengajukan lamaran.', verbose_name='dilamar pada')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Waktu lamaran direview oleh admin/staff.', null=True, verbose_name='direview pada')),
                ('notes', models.TextField(blank=True, help_text='Catatan internal atau feedback untuk pelamar.', verbose_name='catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('applicant', models.ForeignKey(help_text='Pelamar yang melamar pekerjaan ini.', on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='account.applicantprofile', verbose_name='pelamar')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin atau Staff yang mereview lamaran ini.', limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='direview oleh')),
                ('job', models.ForeignKey(help_text='Lowongan kerja yang dilamar.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.lowongankerja', verbose_name='lowongan')),
            ],
            options={
                'verbose_name': 'lamaran kerja',
                'verbose_name_plural': 'daftar lamaran kerja',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul singkat berita.', max_length=255, verbose_name='judul')),
                ('slug', models.SlugField(help_text='Slug unik untuk URL berita.', max_length=255, unique=True, verbose_name='slug')),
                ('summary', models.CharField(blank=True, help_text='Ringkasan singkat yang tampil di daftar berita.', max_length=500, verbose_name='ringkasan')),
                ('content', models.TextField(help_text='Konten lengkap berita (teks HTML/markdown yang sudah diformat).', verbose_name='isi berita')),
                ('hero_image', models.ImageField(blank=True, help_text='Gambar utama opsional untuk ditampilkan di halaman detail berita.', null=True, upload_to='main/news/%Y/%m/', verbose_name='gambar utama')),
                ('status', models.CharField(choices=[('DRAFT', 'Draf'), ('PUBLISHED', 'Dipublikasikan'), ('ARCHIVED', 'Diarsipkan')], db_index=True, default='DRAFT', max_length=10, verbose_name='status')),
                ('is_pinned', models.BooleanField(default=False, help_text='Jika dicentang, berita akan muncul di bagian atas daftar.', verbose_name='sematkan di atas')),
                ('published_at', models.DateTimeField(blank=True, help_text='Waktu ketika berita dipublikasikan.', null=True, verbose_name='dipublikasikan pada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin/Staf yang membuat berita ini.', limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh')),
            ],
            options={
                'verbose_name': 'berita',
                'verbose_name_plural': 'daftar berita',
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lowongankerja',
            index=models.Index(fields=['status', 'employment_type'], name='main_lowong_status_14bce0_idx'),
        ),
        migrations.AddIndex(
            model_name='lowongankerja',
            index=models.Index(fields=['company', 'status'], name='main_lowong_company_ae23e7_idx'),
        ),
        migrations.AddIndex(
            model_name='lowongankerja',
            index=models.Index(fields=['deadline'], name='main_lowong_deadlin_cbb429_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'status'], name='main_jobapp_applica_da4d85_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='main_jobapp_job_id_9e39f8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', 'applied_at'], name='main_jobapp_status_6cb2ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('applicant', 'job'), name='main_jobapplication_unique_applicant_job'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status', 'published_at'], name='main_news_status_aa97fe_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_pinned', 'status'], name='main_news_is_pinn_ff65df_idx'),
        ),
    ]
