# Generated by Django 6.0.2 on 2026-04-06 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchannouncement',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MASTER_ADMIN', 'ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin atau Staff yang memasukkan pelamar ke batch ini.', limit_choices_to={'role__in': ['MASTER_ADMIN', 'ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='ditugaskan oleh'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin atau Staff yang terakhir mengubah status lamaran ini.', limit_choices_to={'role__in': ['MASTER_ADMIN', 'ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='direview oleh'),
        ),
        migrations.AlterField(
            model_name='lamaranbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Staf yang membuat batch ini.', limit_choices_to={'role__in': ['MASTER_ADMIN', 'ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh'),
        ),
        migrations.AlterField(
            model_name='lowongankerja',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Staf/Perusahaan yang membuat lowongan ini.', limit_choices_to={'role__in': ['MASTER_ADMIN', 'ADMIN', 'STAFF', 'COMPANY']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_listings_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Staf yang membuat berita ini.', limit_choices_to={'role__in': ['MASTER_ADMIN', 'ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh'),
        ),
    ]
