# Generated by Django 6.0.2 on 2026-02-11 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_applicantdocument_review_notes_and_more'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Dilamar'), ('UNDER_REVIEW', 'Dalam Review'), ('ACCEPTED', 'Diterima'), ('REJECTED', 'Ditolak')], db_index=True, default='APPLIED', help_text='Status lamaran kerja.', max_length=20, verbose_name='status')),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Waktu pelamar mengajukan lamaran.', verbose_name='dilamar pada')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Waktu lamaran direview oleh admin/staff.', null=True, verbose_name='direview pada')),
                ('notes', models.TextField(blank=True, help_text='Catatan internal atau feedback untuk pelamar.', verbose_name='catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
                ('applicant', models.ForeignKey(help_text='Pelamar yang melamar pekerjaan ini.', on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='account.applicantprofile', verbose_name='pelamar')),
                ('job', models.ForeignKey(help_text='Lowongan kerja yang dilamar.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.lowongankerja', verbose_name='lowongan')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin atau Staff yang mereview lamaran ini.', limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='direview oleh')),
            ],
            options={
                'verbose_name': 'lamaran kerja',
                'verbose_name_plural': 'daftar lamaran kerja',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['applicant', 'status'], name='main_jobapp_applica_da4d85_idx'), models.Index(fields=['job', 'status'], name='main_jobapp_job_id_9e39f8_idx'), models.Index(fields=['status', 'applied_at'], name='main_jobapp_status_6cb2ce_idx')],
                'constraints': [models.UniqueConstraint(fields=('applicant', 'job'), name='main_jobapplication_unique_applicant_job')],
            },
        ),
    ]
