# Generated by Django 6.0.2 on 2026-02-27 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_applicantprofile_heir_contact_phone_and_more'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, help_text='Status sebelum perubahan. Kosong jika ini entri awal pembuatan.', max_length=20, verbose_name='dari status')),
                ('to_status', models.CharField(choices=[('APPLIED', 'Dilamar'), ('UNDER_REVIEW', 'Dalam Review'), ('SHORTLISTED', 'Shortlist'), ('OFFERED', 'Ditawarkan'), ('OFFER_ACCEPTED', 'Tawaran Diterima'), ('OFFER_DECLINED', 'Tawaran Ditolak'), ('PLACED', 'Ditempatkan'), ('COMPLETED', 'Selesai Bekerja'), ('REJECTED', 'Ditolak'), ('WITHDRAWN', 'Dicabut')], help_text='Status setelah perubahan.', max_length=20, verbose_name='ke status')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='diubah pada')),
                ('note', models.TextField(blank=True, verbose_name='catatan')),
            ],
            options={
                'verbose_name': 'riwayat status lamaran',
                'verbose_name_plural': 'riwayat status lamaran',
                'ordering': ['changed_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='main_jobapplication_unique_applicant_job',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin atau Staff yang membuat penugasan ini. Hanya terisi untuk source=ADMIN_ASSIGN.', limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='ditugaskan oleh'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='placement_end_date',
            field=models.DateField(blank=True, db_index=True, help_text='Tanggal pelamar selesai bekerja (kontrak berakhir). Diisi saat status berubah ke COMPLETED. Cooldown 2 tahun dihitung dari tanggal ini.', null=True, verbose_name='tanggal selesai kerja'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(choices=[('SELF_APPLIED', 'Lamar Sendiri'), ('ADMIN_ASSIGN', 'Ditugaskan Admin')], db_index=True, default='SELF_APPLIED', help_text='Apakah pelamar melamar sendiri atau ditugaskan oleh admin.', max_length=20, verbose_name='sumber lamaran'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Waktu pelamar mengajukan lamaran (atau admin membuat penugasan).', verbose_name='dilamar pada'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Waktu terakhir status diubah oleh admin/staff.', null=True, verbose_name='direview pada'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin atau Staff yang terakhir mengubah status lamaran ini.', limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='direview oleh'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Dilamar'), ('UNDER_REVIEW', 'Dalam Review'), ('SHORTLISTED', 'Shortlist'), ('OFFERED', 'Ditawarkan'), ('OFFER_ACCEPTED', 'Tawaran Diterima'), ('OFFER_DECLINED', 'Tawaran Ditolak'), ('PLACED', 'Ditempatkan'), ('COMPLETED', 'Selesai Bekerja'), ('REJECTED', 'Ditolak'), ('WITHDRAWN', 'Dicabut')], db_index=True, default='APPLIED', help_text='Status lamaran kerja saat ini.', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['source', 'status'], name='main_jobapp_source_3ef260_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'status', 'placement_end_date'], name='main_jobapp_applica_8890d7_idx'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='main.jobapplication', verbose_name='lamaran'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='diubah oleh'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['application', 'changed_at'], name='main_applic_applica_208e0a_idx'),
        ),
    ]
