# Generated by Django 6.0.2 on 2026-05-01 17:32

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_applicantprofile_postal_code_fields'),
        ('main', '0006_jobapplication_attendance_by_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Identitas singkat sesi interview, mis. 'Interview 5 Mei 2026 — Sesi Pagi'.", max_length=120, verbose_name='nama sesi interview')),
                ('notes', models.TextField(blank=True, help_text='Catatan internal admin untuk sesi ini.', verbose_name='catatan')),
                ('interview_date', models.DateTimeField(blank=True, db_index=True, help_text='Tanggal dan jam pelaksanaan interview untuk cohort ini.', null=True, verbose_name='tanggal & jam interview')),
                ('interview_location', models.CharField(blank=True, help_text='Lokasi atau link (online/offline) pelaksanaan interview.', max_length=255, verbose_name='lokasi interview')),
                ('interview_notes', models.TextField(blank=True, help_text='Informasi tambahan untuk pelamar (dress code, dokumen, link, dll.).', verbose_name='info interview')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Tandai non-aktif jika sesi sudah selesai dan tidak boleh menerima pelamar baru. Cohort tetap menyimpan riwayat pelamar yang sudah berada di dalamnya.', verbose_name='aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='diperbarui pada')),
            ],
            options={
                'verbose_name': 'sesi interview',
                'verbose_name_plural': 'daftar sesi interview',
                'ordering': ['job', '-interview_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewCohortAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Judul singkat pengumuman, misal: 'Jadwal Interview Diperbarui'.", max_length=200, verbose_name='judul')),
                ('body', models.TextField(help_text='Isi lengkap pengumuman yang akan dibaca oleh pelamar.', verbose_name='isi pesan')),
                ('recipient_config', models.JSONField(default=main.models.default_interview_cohort_announcement_recipient_config, help_text='Siapa yang menerima notifikasi & melihat pengumuman, mis. {"selection_type": "all_active"} atau {"selection_type": "statuses", "statuses": ["INTERVIEW","DITERIMA"]}.', verbose_name='konfigurasi penerima')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='dibuat pada')),
            ],
            options={
                'verbose_name': 'pengumuman sesi interview',
                'verbose_name_plural': 'daftar pengumuman sesi interview',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='lamaranbatch',
            options={'ordering': ['job', 'tahap_order', '-created_at'], 'verbose_name': 'batch lamaran (tahap pra-seleksi)', 'verbose_name_plural': 'daftar batch lamaran (tahap pra-seleksi)'},
        ),
        migrations.RemoveIndex(
            model_name='lamaranbatch',
            name='main_lamara_intervi_8610a1_idx',
        ),
        migrations.AddField(
            model_name='lamaranbatch',
            name='tahap_label',
            field=models.CharField(blank=True, help_text="Label deskriptif untuk tahapan, mis. 'Pra-Seleksi 1: CV Screening'. Opsional; jika kosong, frontend menampilkan 'Pra-Seleksi {tahap_order}'.", max_length=120, verbose_name='label tahapan'),
        ),
        migrations.AddField(
            model_name='lamaranbatch',
            name='tahap_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Urutan tahapan pra-seleksi dalam lowongan ini (1 = tahap pertama). Lowongan dapat memiliki banyak tahapan pra-seleksi (mis. CV → Psikotes → FGD). Tidak harus unik — admin bisa membuat sub-batch paralel pada tahap yang sama.', verbose_name='urutan tahapan'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch (tahap pra-seleksi) tempat pelamar ini sedang berada. Dapat dipindahkan antar batch saat masih di status PRA_SELEKSI.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.lamaranbatch', verbose_name='batch pra-seleksi'),
        ),
        migrations.AlterField(
            model_name='lamaranbatch',
            name='interview_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='DEPRECATED. Jadwal interview kini disimpan di InterviewCohort. Kolom ini hanya dipakai sebagai fallback untuk data lama.', null=True, verbose_name='tanggal & jam interview (deprecated)'),
        ),
        migrations.AlterField(
            model_name='lamaranbatch',
            name='interview_location',
            field=models.CharField(blank=True, help_text='DEPRECATED. Lihat InterviewCohort.interview_location.', max_length=255, verbose_name='lokasi interview (deprecated)'),
        ),
        migrations.AlterField(
            model_name='lamaranbatch',
            name='interview_notes',
            field=models.TextField(blank=True, help_text='DEPRECATED. Lihat InterviewCohort.interview_notes.', verbose_name='info interview (deprecated)'),
        ),
        migrations.AddIndex(
            model_name='lamaranbatch',
            index=models.Index(fields=['job', 'tahap_order'], name='main_lamara_job_id_63def3_idx'),
        ),
        migrations.AddField(
            model_name='interviewcohort',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Staf yang membuat sesi interview ini.', limit_choices_to={'role__in': ['MASTER_ADMIN', 'ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_cohorts_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh'),
        ),
        migrations.AddField(
            model_name='interviewcohort',
            name='job',
            field=models.ForeignKey(help_text='Lowongan tempat sesi interview ini diadakan.', on_delete=django.db.models.deletion.CASCADE, related_name='interview_cohorts', to='main.lowongankerja', verbose_name='lowongan'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_cohort',
            field=models.ForeignKey(blank=True, help_text='Cohort interview tempat pelamar ini ditempatkan saat dipindahkan ke status INTERVIEW. Sejak status INTERVIEW ke atas, semua aksi bulk (transition, announcement, export) dilakukan pada cohort, bukan lagi pada batch.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='main.interviewcohort', verbose_name='sesi interview'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['interview_cohort', 'status'], name='main_jobapp_intervi_362988_idx'),
        ),
        migrations.AddField(
            model_name='interviewcohortannouncement',
            name='cohort',
            field=models.ForeignKey(help_text='Cohort interview penerima pengumuman ini.', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='main.interviewcohort', verbose_name='sesi interview'),
        ),
        migrations.AddField(
            model_name='interviewcohortannouncement',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MASTER_ADMIN', 'ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='dibuat oleh'),
        ),
        migrations.AddIndex(
            model_name='interviewcohort',
            index=models.Index(fields=['job', 'is_active'], name='main_interv_job_id_2c082d_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewcohort',
            index=models.Index(fields=['interview_date'], name='main_interv_intervi_6823d9_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewcohortannouncement',
            index=models.Index(fields=['cohort', 'created_at'], name='main_interv_cohort__def873_idx'),
        ),
    ]
