# Generated by Django 6.0.2 on 2026-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_add_diterima_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='diterima_current_step',
            field=models.CharField(choices=[('MASUK_BERKAS_ASLI', 'Masuk Berkas Asli'), ('MEDICAL', 'Medical'), ('BUAT_ID_PEKERJA', 'Buat ID Pekerja'), ('BUAT_PASPOR', 'Buat Paspor'), ('FWCMS', 'FWCMS'), ('PSIKOLOGI_TEST', 'Psikologi Test'), ('PAP_BP3MI', 'PAP BP3MI'), ('PDO_KILANG', 'PDO Kilang'), ('PERSIAPAN_KEBERANGKATAN', 'Persiapan Keberangkatan')], db_index=True, default='MASUK_BERKAS_ASLI', help_text='Posisi pelamar dalam alur sub-tahapan Diterima (9 langkah berurutan). Dimulai dari Masuk Berkas Asli, diakhiri Persiapan Keberangkatan. Dikendalikan oleh admin; setelah langkah terakhir, admin dapat memindahkan ke tahap Berangkat.', max_length=30, verbose_name='sub-tahapan diterima saat ini'),
        ),
    ]
