# Generated by Django 6.0.2 on 2026-07-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_jobapplication_transfer_and_transferred_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='from_status',
            field=models.CharField(blank=True, help_text='Status sebelum perubahan. Kosong jika ini entri awal pembuatan.', max_length=15, verbose_name='dari status'),
        ),
    ]
