#!/bin/bash
# Install automatic TLS renewal for KMS-Connect.
#
# Installs:
#   1) /etc/letsencrypt/renewal-hooks/deploy/kms-connect.sh  (works with systemd certbot.timer)
#   2) /etc/cron.d/kms-connect-certbot                       (when root; belt-and-suspenders)
#   3) user crontab calling deploy/ssl-renew.sh              (when not root but docker available)
#
# Also migrates Let's Encrypt renewal from standalone → webroot when needed
# (standalone fails while docker nginx holds port 80).
#
# Usage (on production server, from repo):
#   sudo ./deploy/install-ssl-auto-renewal.sh   # preferred
#   ./deploy/install-ssl-auto-renewal.sh        # docker/user-cron fallback

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(dirname "$SCRIPT_DIR")"
DOMAIN="${SSL_DOMAIN:-data.kms-connect.com}"
HOOK="$APP_DIR/deploy/ssl-renew-deploy-hook.sh"
RENEW_SCRIPT="$APP_DIR/deploy/ssl-renew.sh"
LOG_FILE="/var/log/kms-connect-certbot.log"
USER_LOG="${HOME:-/tmp}/kms-connect-certbot.log"
RENEWAL_CONF="/etc/letsencrypt/renewal/${DOMAIN}.conf"
WEBROOT="/var/www/certbot"
IS_ROOT=0
if [ "${EUID:-0}" -eq 0 ]; then
  IS_ROOT=1
fi

if [ ! -f "$HOOK" ] || [ ! -f "$RENEW_SCRIPT" ]; then
  echo "Missing renew scripts under $APP_DIR/deploy" >&2
  exit 1
fi
chmod +x "$HOOK" "$RENEW_SCRIPT"

ensure_webroot_dir() {
  mkdir -p "$WEBROOT" 2>/dev/null || docker run --rm -v /var/www/certbot:/var/www/certbot alpine mkdir -p /var/www/certbot
  chmod 755 "$WEBROOT" 2>/dev/null || true
}

renewal_is_standalone() {
  if [ -r "$RENEWAL_CONF" ]; then
    grep -qE '^[[:space:]]*authenticator[[:space:]]*=[[:space:]]*standalone[[:space:]]*$' "$RENEWAL_CONF"
    return $?
  fi
  docker run --rm -v /etc/letsencrypt:/etc/letsencrypt:ro alpine \
    grep -qE '^[[:space:]]*authenticator[[:space:]]*=[[:space:]]*standalone[[:space:]]*$' \
    "/etc/letsencrypt/renewal/${DOMAIN}.conf" 2>/dev/null
}

migrate_to_webroot_if_needed() {
  if ! renewal_is_standalone; then
    return 0
  fi
  echo "Migrating $DOMAIN renewal authenticator: standalone → webroot..."
  FORCE_SSL_RENEWAL=1 bash "$RENEW_SCRIPT"
}

install_letsencrypt_deploy_hook() {
  # Systemd certbot.timer runs `certbot renew` without our --deploy-hook flag.
  # Install a tiny wrapper that execs the repo hook by absolute path (do NOT
  # copy the hook itself — it resolves APP_DIR from its own location).
  local dest="/etc/letsencrypt/renewal-hooks/deploy/kms-connect-deploy-hook.sh"
  local wrapper_file
  wrapper_file="$(mktemp)"
  cat >"$wrapper_file" <<EOF
#!/bin/bash
# Auto-generated by install-ssl-auto-renewal.sh — do not edit.
exec "$HOOK" "\$@"
EOF
  if [ "$IS_ROOT" -eq 1 ]; then
    mkdir -p /etc/letsencrypt/renewal-hooks/deploy
    cp "$wrapper_file" "$dest"
    chmod 755 "$dest"
  else
    docker run --rm \
      -v /etc/letsencrypt:/etc/letsencrypt \
      -v "$wrapper_file:/wrapper.sh:ro" \
      alpine sh -c "
        mkdir -p /etc/letsencrypt/renewal-hooks/deploy
        cp /wrapper.sh '$dest'
        chmod 755 '$dest'
      "
  fi
  rm -f "$wrapper_file"
  echo "Installed $dest → $HOOK"
}

install_root_cron() {
  local cron_file="/etc/cron.d/kms-connect-certbot"
  cat > "$cron_file" <<EOF
# KMS-Connect — Let's Encrypt renew + deploy hook (PEM copy + nginx reload)
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

12 3,15 * * * root $RENEW_SCRIPT >>$LOG_FILE 2>&1
EOF
  chmod 644 "$cron_file"
  touch "$LOG_FILE"
  chmod 640 "$LOG_FILE" 2>/dev/null || true
  rm -f /etc/cron.daily/kms-connect-renew-ssl /etc/cron.monthly/renew-ssl-cert
  echo "Installed $cron_file (03:12 and 15:12)"
}

install_user_cron() {
  local marker="# kms-connect-ssl-renew"
  local line="12 3,15 * * * $RENEW_SCRIPT >>$USER_LOG 2>&1 $marker"
  local tmp
  tmp="$(mktemp)"
  # Keep other crontab lines; replace any previous marker line
  crontab -l 2>/dev/null | grep -v 'kms-connect-ssl-renew' >"$tmp" || true
  echo "$line" >>"$tmp"
  crontab "$tmp"
  rm -f "$tmp"
  touch "$USER_LOG" 2>/dev/null || true
  echo "Installed user crontab entry for $(whoami) (log: $USER_LOG)"
}

if ! grep -q '/var/www/certbot:/var/www/certbot' "$APP_DIR/docker-compose.prod.yml" 2>/dev/null; then
  echo "WARNING: nginx should mount host /var/www/certbot for HTTP-01 webroot renewals." >&2
  echo "  Add under nginx volumes: - /var/www/certbot:/var/www/certbot:ro" >&2
fi

ensure_webroot_dir
migrate_to_webroot_if_needed
install_letsencrypt_deploy_hook

if [ "$IS_ROOT" -eq 1 ]; then
  install_root_cron
else
  echo "Not root — skipping /etc/cron.d (optional). Installing user crontab + relying on certbot.timer + deploy hook."
  if command -v crontab >/dev/null 2>&1; then
    install_user_cron
  fi
fi

echo ""
echo "Auto-renewal installed."
echo "  Hook script: $HOOK"
echo "  Renew script: $RENEW_SCRIPT"
echo "  Test: $RENEW_SCRIPT"
echo "  Dry-run (root): certbot renew --dry-run"
echo "  Dry-run (docker): docker run --rm -v /etc/letsencrypt:/etc/letsencrypt -v $WEBROOT:$WEBROOT certbot/certbot renew --dry-run"
