// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMeT7jLv8mwU9SZQOSClAq3OIvNaUsEGQ',
    appId: '1:268800410479:web:080939a767509011d95e9a',
    messagingSenderId: '268800410479',
    projectId: 'kms-connect-1541d',
    authDomain: 'kms-connect-1541d.firebaseapp.com',
    storageBucket: 'kms-connect-1541d.firebasestorage.app',
    measurementId: 'G-2LVN0NH4R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzljkImZNbmkZE7O6GNETp9ewuaYcb9lQ',
    appId: '1:268800410479:android:45bdfc7a6ff82c16d95e9a',
    messagingSenderId: '268800410479',
    projectId: 'kms-connect-1541d',
    storageBucket: 'kms-connect-1541d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2wMY102bCN3NhOU_jj3DZYKGeFVqLiRQ',
    appId: '1:268800410479:ios:82733280c4b92578d95e9a',
    messagingSenderId: '268800410479',
    projectId: 'kms-connect-1541d',
    storageBucket: 'kms-connect-1541d.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2wMY102bCN3NhOU_jj3DZYKGeFVqLiRQ',
    appId: '1:268800410479:ios:82733280c4b92578d95e9a',
    messagingSenderId: '268800410479',
    projectId: 'kms-connect-1541d',
    storageBucket: 'kms-connect-1541d.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMeT7jLv8mwU9SZQOSClAq3OIvNaUsEGQ',
    appId: '1:268800410479:web:fd025de608a5cc04d95e9a',
    messagingSenderId: '268800410479',
    projectId: 'kms-connect-1541d',
    authDomain: 'kms-connect-1541d.firebaseapp.com',
    storageBucket: 'kms-connect-1541d.firebasestorage.app',
    measurementId: 'G-JP4Y3XQXML',
  );
}